name: test-suite

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main
    - 'releases/**'
  schedule:
    - cron: '30 22 * * 0,3'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: dglaeser/compiler-images:${{ matrix.compiler }}
    strategy:
      matrix:
          compiler: [gcc-14, clang-19-git]
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        with:
          submodules: true

      # install of make can be omitted once the container provides it per default
      - name: build-tests
        run: |
          apt update && apt install -y make libeigen3-dev
          echo "Using C compiler ${C_COMPILER}"
          echo "Using C++ compiler ${CXX_COMPILER}"
          cmake -DCMAKE_C_COMPILER=${C_COMPILER} \
                -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
                -DADAC_BUILD_BENCHMARK=ON \
                -B build
          cmake --build build

      - name: run-tests
        run: cd build && ctest --output-on-failure

  test-installed-package:
    runs-on: ubuntu-22.04
    container: dglaeser/compiler-images:gcc-14
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        with:
          submodules: true

      # install of make can be omitted once the container provides it per default
      - name: install-library
        run: |
          apt update && apt install make
          echo "Using C compiler ${C_COMPILER}"
          echo "Using C++ compiler ${CXX_COMPILER}"
          cmake -DCMAKE_C_COMPILER=${C_COMPILER} \
                -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
                -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
                -DADAC_BUILD_TESTS=OFF \
                -B build
          cmake --build build
          cmake --install build

      - name: make-test-project
        run: |
          mkdir test_project
          cp -r test test_project/
          cd test_project
          echo "cmake_minimum_required(VERSION 3.18)" > CMakeLists.txt
          echo "project(adac_test_suite)" >> CMakeLists.txt
          echo "find_package(adac REQUIRED)" >> CMakeLists.txt
          echo "add_subdirectory(test)" >> CMakeLists.txt
          cd ..

      - name: build-test-project
        run: |
          cd test_project
          cmake -DCMAKE_C_COMPILER=${C_COMPILER} \
                -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
                -Dadac_ROOT=$(pwd)/../install \
                -B build
          cmake --build build
          cd ..

      - name: run-tests
        run: cd test_project/build && ctest --output-on-failure
