name: test-suite

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main
    - 'releases/**'
  schedule:
    - cron: '30 22 * * 0,3'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc-14, clang-18]
        include:
          - benchmark: ON
            compiler: gcc-14
          - c_compiler: gcc-14
            compiler: gcc-14
          - cxx_compiler: g++-14
            compiler: gcc-14
          - benchmark: ON
            compiler: clang-18
          - c_compiler: clang-18
            compiler: clang-18
          - cxx_compiler: clang++-18
            compiler: clang-18
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build-tests
        run: |
          sudo apt install libeigen3-dev
          cmake -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} \
                -DADAC_BUILD_BENCHMARK=${{ matrix.benchmark }} \
                -B build
          cmake --build build

      - name: run-tests
        run: cd build && ctest --output-on-failure

  test-installed-package:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-library
        run: |
          sudo apt install libeigen3-dev
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
                -DADAC_BUILD_TESTS=OFF \
                -B build
          cmake --build build
          cmake --install build

      - name: make-test-project
        run: |
          mkdir test_project
          cp -r test test_project/
          cd test_project
          echo "cmake_minimum_required(VERSION 3.18)" > CMakeLists.txt
          echo "project(adac_test_suite)" >> CMakeLists.txt
          echo "find_package(adac REQUIRED)" >> CMakeLists.txt
          echo "add_subdirectory(test)" >> CMakeLists.txt
          cd ..

      - name: build-test-project
        run: |
          cd test_project
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -Dadac_ROOT=$(pwd)/../install \
                -B build
          cmake --build build
          cd ..

      - name: run-tests
        run: cd test_project/build && ctest --output-on-failure
